name: Blob Build Master
on:
  push:
    branches:
      - master

jobs:
  build:
    steps: 
    - uses: actions/checkout@master
    - uses: lauchacarro/Azure-Storage-Action@master
      with:
        connection-string: ${{ secrets.CONNECTION_STRING }}