name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          cat $HOME/files_removed.json
          echo '${{ steps.file_changes.outputs.files}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
          echo '${{ steps.file_changes.outputs.files_removed}}'
      - uses: actions/checkout@v1
      - run: mkdir -p path/to/artifact
      - run: HOMEDIR=$HOME npm run move
      - run: cp ./pdf/19-11069-Natomas-LLC.pdf path/to/artifact/
      - uses: StateOfCalifornia/azblob-upload-artifact@master     
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container: '$web'
          path: path/to/artifact
          name: pdf
          cleanup: false
          sync: false
